spring:
  datasource:
    url: { DB_URL }
    username: { DB_USERNAME }
    password: { DB_PASSWORD }
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}



  mail:
    host: { MAIL_HOST }
    port: { MAIL_PORT }
    username: { MAIL_USERNAME }
    password: { MAIL_PASSWORD }
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}


storage:
  location: ${STORAGE_LOCATION}